ExamSecondTry/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExamSecondTry.Context;
using ExamSecondTry.Models;

namespace ExamSecondTry.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly ContextDb _context;

        public EmployeesController(ContextDb context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
              return _context.Employess != null ? 
                          View(await _context.Employess.ToListAsync()) :
                          Problem("Entity set 'ContextDb.Employess'  is null.");
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.Employess == null)
            {
                return NotFound();
            }

            var employee = await _context.Employess
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Document,Name,Surname,City,Address,Location,Email,Phone,Status")] Employee employee)
        {
            if (ModelState.IsValid)
            {
                employee.Id = Guid.NewGuid();
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.Employess == null)
            {
                return NotFound();
            }

            var employee = await _context.Employess.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,Document,Name,Surname,City,Address,Location,Email,Phone,Status")] Employee employee)
        {
            if (id != employee.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employee);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employee.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employee);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.Employess == null)
            {
                return NotFound();
            }

            var employee = await _context.Employess
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.Employess == null)
            {
                return Problem("Entity set 'ContextDb.Employess'  is null.");
            }
            var employee = await _context.Employess.FindAsync(id);
            if (employee != null)
            {
                _context.Employess.Remove(employee);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(Guid id)
        {
          return (_context.Employess?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ExamSecondTry/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>@ViewData["Title"] - ExamSecondTry</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="~/assets/img/favicon.png" rel="icon">
  <link href="~/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="~/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="~/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.snow.css" rel="stylesheet">
  <link href="~/assets/vendor/quill/quill.bubble.css" rel="stylesheet">
  <link href="~/assets/vendor/remixicon/remixicon.css" rel="stylesheet">
  <link href="~/assets/vendor/simple-datatables/style.css" rel="stylesheet">

  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
  <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
  <link rel="stylesheet" href="~/ExamSecondTry.styles.css" asp-append-version="true" />

  <!-- Template Main CSS File -->
  <link href="~/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: NiceAdmin
  * Updated: Mar 09 2023 with Bootstrap v5.2.3
  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top d-flex align-items-center">

    <div class="d-flex align-items-center justify-content-between">
      <a asp-area="" asp-controller="Home" asp-action="Index"class="logo d-flex align-items-center">
        <img src="~/assets/img/logo.png" alt="">
        <span class="d-none d-lg-block">ExamSecondTry</span>
      </a>
      @if (SignInManager.IsSignedIn(User))
            {
                <i class="bi bi-list toggle-sidebar-btn"></i>
            }
    </div><!-- End Logo -->

    <nav class="header-nav ms-auto">
      <ul class="d-flex align-items-center">        

          @if (SignInManager.IsSignedIn(User))
            {
                        <li class="nav-item">
                    <span>bienvenido @UserManager.GetUserName(User)!</span>
                </li>

                <li class="nav-item">
                    <form id="logoutForm" class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                        <button id="logout" type="submit" class="nav-link btn btn-link text-dark">Cerrar Sesion</button>
                    </form>
                </li>  
            } else
            {
                 <li class="nav-item">
                    <a class="nav-link text-dark" id="login" asp-area="Identity" asp-page="/Account/Login">Ingresar</a>
                </li>       
                <li class="nav-item">
                    <a class="nav-link text-dark" id="register" asp-area="Identity" asp-page="/Account/Register">Registrar</a>
                </li>
            }


        

        @*<li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            <img src="~/assets/img/profile-img.jpg" alt="Profile" class="rounded-circle">
            <span class="d-none d-md-block dropdown-toggle ps-2">K. Anderson</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">



            <li class="dropdown-header">
              <h6>Kevin Anderson</h6>
              <span>Web Designer</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>            

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class="bi bi-box-arrow-right"></i>
                <span>Cerrar Sesion</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->*@

      </ul>
    </nav><!-- End Icons Navigation -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  @if (SignInManager.IsSignedIn(User))
    {
        
    
    <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

      <li class="nav-item">
          @if(ViewData["Title"] == "Home Page")
            {
                <a class="nav-link"  asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-grid"></i>
                    <span>Inicio</span>
                </a>              
            } else {
                <a class="nav-link collapsed"  asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-grid"></i>
                    <span>Inicio</span>
                </a>              
            }

      </li><!-- End Dashboard Nav -->      

      <li class="nav-item">

           @if(ViewData["Title"] == "Empleados")
            {               

                <a class="nav-link"  asp-area="" asp-controller="Employees" asp-action="Index">
                    <i class="bi bi-grid"></i>
                    <span>Empleados</span>
                </a>              
            } else {
                <a class="nav-link collapsed"  asp-area="" asp-controller="Employees" asp-action="Index">
                    <i class="bi bi-grid"></i>
                    <span>Empleados</span>
                </a>              
            }              
      </li>
    </ul>

  </aside><!-- End Sidebar-->
  }
    
  <main id="main" class="main">

    <!-- <div class="pagetitle">
      <h1>Dashboard</h1>      
    </div>End Page Title -->        

    <section class="section dashboard">
      <div class="row">
        @RenderBody()
      </div>
    </section>

  </main><!-- End #main -->

  

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="~/assets/vendor/apexcharts/apexcharts.min.js"></script>
  <script src="~/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="~/assets/vendor/chart.js/chart.umd.js"></script>
  <script src="~/assets/vendor/echarts/echarts.min.js"></script>
  <script src="~/assets/vendor/quill/quill.min.js"></script>
  <script src="~/assets/vendor/simple-datatables/simple-datatables.js"></script>
  <script src="~/assets/vendor/tinymce/tinymce.min.js"></script>
  <script src="~/assets/vendor/php-email-form/validate.js"></script>

  <script src="~/lib/jquery/dist/jquery.min.js"></script>
  <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="~/js/site.js" asp-append-version="true"></script>
  @await RenderSectionAsync("Scripts", required: false)

  <!-- Template Main JS File -->
  <script src="~/assets/js/main.js"></script>

</body>

</html>